### PR TITLE
Stage 1 React and Third-Party API

### PR DESCRIPTION
**Pull request by skovakina**
**The website has two main features:**
- When the user enters a keyword in the search bar, the website sends a request to the News API service, finds all the relevant articles over the last week, and displays a list of cards for each of them.
- It displays all articles a user saves in a special section of the website.

**The front end of the website consists of two pages:**
- The main page with a search box
- The page with saved news items where all the liked materials are displayed

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review, it looks great! I left several comments below and hope that they can help you to improve your project and get more points. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * All fonts aren't linked to the project, you should remove alternative fonts from `@font-face` rules, alternative fonts should be added only in custom css selectors
    * Mismatches of the main page on 1440px https://pasteboard.co/dUF9lIPaULoF.png https://pasteboard.co/iSvb6ufGhpyB.png
    * Mismatches of the main page on 768px https://pasteboard.co/AeuCBl4P5gOy.png https://pasteboard.co/GsveN7T6KehG.png https://pasteboard.co/0JrmharmXhAz.png
    * Mismatches of the main page on 320px https://pasteboard.co/VoFXhtKU7AcH.png https://pasteboard.co/rZ0aahAaxYxA.png https://pasteboard.co/9t2eGk1tceMV.png
    * Mismatches of the saved news page on 1440px https://pasteboard.co/fQfalNCQtYn8.png
    * Mismatches of the saved news page on 768px https://pasteboard.co/zX28q1hBuLDc.png
    * You should also fix the info of saved news page on 320 viewport - please check all sizes, spaces and text properties
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * About title should be centered horizontally on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * There shouldn't be capital letters in class names
    * BEM element shouldn't be used outside of its block (for example `search__container` shouldn't be used outside `search` block class). Please fix all similar cases **throughout the project**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [ ] A `components` folder with JS and CSS files for the components.
      * css files should be moved into `components` with corresponding components folders
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * You have lintitng warnings and also errors in the browser console

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 66

## Additional comments:
- Sometimes news cards don't have images, it will be great to add placeholder images for such cards

**Comment by skovakina** [comment]
Hello!
First off, I truly appreciate the time and effort you put into reviewing my code. Every review session is an invaluable learning opportunity for me, and I'm grateful for the insights you share.

I have a question that I hope you won't mind helping me with. During the course, I learned about organizing project files, specifically using a single block folder for all my CSS and a separate component folder for all my JS. I've also consulted my tutor on this matter, and they confirmed that this structure is acceptable for the final project.

However, I'm keen to follow best practices and make my projects better. What do you think about organizing files this way? 

Thank you once again for your guidance and support. Looking forward to your feedback!

**Comment by FiLLa-FaS** [comment]
Hi! Thank you for your kind words!
About the file structure: actually project structure is pretty volatile, it depends on the project size, your company standards or team you work with, there's no only one right option. I work with base checklist standards, but I can add these points, because I see that you've chosen this file structure consciously and consult with the tutor. Thank you!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches of the main page on 768px https://pasteboard.co/D9P4bsFcBzBo.png https://pasteboard.co/8DRTFW0odxzR.png https://pasteboard.co/W5PLLoy6cgUo.png
    * Mismatches of the main page on 320px https://pasteboard.co/yvlwQFq8ZI7W.png https://pasteboard.co/KHPlGqEVG58T.png https://pasteboard.co/T6eWX5AIQumV.png
    * Item with keywords should be added to saved-news header after the header title
    * Incorrect text properties of the `saved-news-header__sub-title` on 768 viewport
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * About section and its content should be centered horizontally on intermediate screen resolutions (please check the mobile screen resolutions)
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * You have lintitng warnings and also errors in the browser console https://pasteboard.co/915Stgshteeq.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 70

**Comment by skovakina** [comment]
Thank you so much for your insight on the project structure!
I've addressed and fixed the layout issues that were highlighted. Looking forward to your feedback!

**Comment by FiLLa-FaS** [comment]
Hi! You've done an exellent job and I'm happy to accept your project. Good luck on the next diploma stage!🙌🚀

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * You have lintitng warnings and also errors in the browser console https://pasteboard.co/915Stgshteeq.png

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 96

## Additional comments:
- Note, that sometimes placeholder image looks different in certain cards https://pasteboard.co/bdJDPJK5APAX.png

**Pull request merged**
